apitoken: <put your SmartThings API token here>
monitor:
  - light
  - temperatureMeasurement
  - illuminanceMeasurement
  - relativeHumidityMeasurement
  - ultravioletIndex
period: 120
influxurl: http://localhost:8086
influxtoken: token
influxorg: org
influxbucket: bucket
valuemap:
  switch:
    off: 0
    on: 1
