version: '2'
services:
  monitor:
    image: eargollo/smartthings-influx:latest
    environment:
      - APITOKEN
    volumes:
      - ./smartthings-influx-compose.yaml:/.smartthings-influx.yaml
    command: monitor
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:2.7
    ports:
      - '8086:8086'
    volumes:
      - ./data/influxdb2-data:/var/lib/influxdb2
      - ./data/influxdb2-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=SmartThings
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
  # chronograf:
  #   image: chronograf:latest
  #   ports:
  #     - '127.0.0.1:8888:8888'
  #   volumes:
  #     - ./data/influxdb:/var/lib/chronograf
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=http://influxdb:8086
  #     - INFLUXDB_USERNAME=admin
  #     - INFLUXDB_PASSWORD=password
  grafana:
    user: "${UID}:${GID}"
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
