apitoken: <put your smartthings api token here or set APITOKEN env var>
monitor:
  - temperatureMeasurement
  - illuminanceMeasurement
  - relativeHumidityMeasurement
  - ultravioletIndex
smartthings:
  capabilities:
    - name: switch
      time: wall
period: 10
influxurl: http://influxdb:8086
influxtoken: token
influxorg: org
influxbucket: SmartThings
valuemap:
  switch:
    off: 0
    on: 1